### PR TITLE
Project readme

### PR DESCRIPTION
**Pull request by aoswalt**

### CODE REVIEW

**Comment by Seeker1911** [comment]
👍

**Comment by Seeker1911** [comment]
👍

**Comment by Seeker1911** [comment]
💯

**Comment by AlanE23** [comment]
📟 🎯 :octocat:

**Comment by josephkane** [comment]
👚

**Comment by josephkane** [comment]
🐡

**Comment by AlanE23** [comment]
:neckbeard:

**Comment by Seeker1911** [comment]
💽

**Comment by josephkane** [comment]
🍖

**Comment by AlanE23** [comment]
🔨

**Pull request merged**
